### ISSUE TITLE
genymotion device stop

### ISSUE THREAD

**Issue by randinfo** [yshinkarev/my-bash#1]
hi, my device got corrupted when i use the player -n "name" -x command. It stops the device. but when i restart it via player --vm-name name it never starts.

Is the an issue with it ?

**Comment by yshinkarev** [comment]
Hi. What OS do you have?
What do you see in logs on command:
`player --vm-name "${VM_NAME}"`

**Comment by amarCosmospace** [comment]
i'm using mac os. it seem that when i do player -n "name" it starts the vm and when i do player -n "name" -x it doesnt stop it. But anyway the bug is not present anymore, maybe some weird bug
